In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('quikr_car.csv')
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,"80,000","45,000 kms",Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,"4,25,000",40 kms,Diesel
2,Maruti Suzuki Alto 800 Vxi,Maruti,2018,Ask For Price,"22,000 kms",Petrol
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,"3,25,000","28,000 kms",Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,"5,75,000","36,000 kms",Diesel

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB

In [4]:
df.shape

(892, 6)

##### Quality Check

In [5]:
df['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [6]:
df['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,500',
       '2,51,111', '5,69,999', '69,999', '2,99,999', '3,99,999',
       '4,50,000', '2,70,000', '1,58,400', '1,79,000', '1,25,000',
       '2,99,000', '1,50,000', '2,75,000', '2,85,000', '3,40,000',
       '70,000', '2,89,999', '8,49,999', '7,49,999', '2,74,999',
       '9,84,999', '5,99,999', '2,44,999', '4,74,999', '2,45,000',
       '1,69,500', '3,70,000', '1,68,000', '1,45,000', '98,500',
       '2,09,000', '1,85,000', '9,00,000', '6,99,999', '1,99,999',
       '5,44,999', '1,99,000', '5,40,000', '49,000', '7,00,000', '55,000',
       '8,95,000', '3,55,000', '5,65,000', '3,65,000', '40,000',
       '4,00,000', '3,30,000', '5,80,000', '3,79,000', '2,19,000',
       '5,19,000', '7,30,000', '20,00,000', '21,00,000', '14,00,000',
       '3,11,000', '8,55,000', '5,35,000', '1,78,000', '3,00,000',
       '2,55,000', '5,49,999', '3,80,000', '57,000', '4,10,000',
       '2,25,000', '1,20,000', '59,000', '5,99,000', '6,75,000', '72,500',
       '6,10,000', '2,30,000', '5,20,000', '5,24,999', '4,24,999',
       '6,44,999', '5,84,999', '7,99,999', '4,44,999', '6,49,999',
       '9,44,999', '5,74,999', '3,74,999', '1,30,000', '4,01,000',
       '13,50,000', '1,74,999', '2,39,999', '99,999', '3,24,999',
       '10,74,999', '11,30,000', '1,49,000', '7,70,000', '30,000',
       '3,35,000', '3,99,000', '65,000', '1,69,999', '1,65,000',
       '5,60,000', '9,50,000', '7,15,000', '45,000', '9,40,000',
       '1,55,555', '15,00,000', '4,95,000', '8,00,000', '12,99,000',
       '5,30,000', '14,99,000', '32,000', '4,05,000', '7,60,000',
       '7,50,000', '4,19,000', '1,40,000', '15,40,000', '1,23,000',
       '4,98,000', '4,80,000', '4,88,000', '15,25,000', '5,48,900',
       '7,25,000', '99,000', '52,000', '28,00,000', '4,99,000',
       '3,81,000', '2,78,000', '6,90,000', '2,60,000', '90,001',
       '1,15,000', '15,99,000', '1,59,000', '51,999', '2,15,000',
       '35,000', '11,50,000', '2,69,000', '60,000', '4,30,000',
       '85,00,003', '4,01,919', '4,90,000', '4,24,000', '2,05,000',
       '5,49,900', '3,71,500', '4,35,000', '1,89,700', '3,89,700',
       '3,60,000', '2,95,000', '1,14,990', '10,65,000', '4,70,000',
       '48,000', '1,88,000', '4,65,000', '1,79,999', '21,90,000',
       '23,90,000', '10,75,000', '4,75,000', '10,25,000', '6,15,000',
       '19,00,000', '14,90,000', '15,10,000', '18,50,000', '7,90,000',
       '17,25,000', '12,25,000', '68,000', '9,70,000', '31,00,000',
       '8,99,000', '88,000', '53,000', '5,68,500', '71,000', '5,90,000',
       '7,95,000', '42,000', '1,89,000', '1,62,000', '35,999',
       '29,00,000', '39,999', '50,500', '5,10,000', '8,60,000',
       '5,00,001'], dtype=object)

In [7]:
df['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [8]:
df['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,600 kms', '7,500 kms', '26,000 kms',
       '24,330 kms', '65,480 kms', '28,028 kms', '2,00,000 kms',
       '99,000 kms', '2,800 kms', '21,000 kms', '11,000 kms',
       '66,000 kms', '3,000 kms', '7,000 kms', '38,500 kms', '37,200 kms',
       '43,200 kms', '24,800 kms', '45,872 kms', '40,000 kms',
       '11,400 kms', '97,200 kms', '52,000 kms', '31,000 kms',
       '1,75,430 kms', '37,000 kms', '65,000 kms', '3,350 kms',
       '75,000 kms', '62,000 kms', '73,000 kms', '2,200 kms',
       '54,870 kms', '34,580 kms', '97,000 kms', '60 kms', '80,200 kms',
       '3,200 kms', '0,000 kms', '5,000 kms', '588 kms', '71,200 kms',
       '1,75,400 kms', '9,300 kms', '56,758 kms', '10,000 kms',
       '56,450 kms', '56,000 kms', '32,700 kms', '9,000 kms', '73 kms',
       '1,60,000 kms', '84,000 kms', '58,559 kms', '57,000 kms',
       '1,70,000 kms', '80,000 kms', '6,821 kms', '23,000 kms',
       '34,000 kms', '1,800 kms', '4,00,000 kms', '48,000 kms',
       '90,000 kms', '12,000 kms', '69,900 kms', '1,66,000 kms',
       '122 kms', '0 kms', '24,000 kms', '36,469 kms', '7,800 kms',
       '24,695 kms', '15,141 kms', '59,910 kms', '1,00,000 kms',
       '4,500 kms', '1,29,000 kms', '300 kms', '1,31,000 kms',
       '1,11,111 kms', '59,466 kms', '25,500 kms', '44,005 kms',
       '2,110 kms', '43,222 kms', '1,00,200 kms', '65 kms',
       '1,40,000 kms', '1,03,553 kms', '58,000 kms', '1,20,000 kms',
       '49,800 kms', '100 kms', '81,876 kms', '6,020 kms', '55,700 kms',
       '18,500 kms', '1,80,000 kms', '53,000 kms', '35,500 kms',
       '22,134 kms', '1,000 kms', '8,500 kms', '87,000 kms', '6,000 kms',
       '15,574 kms', '8,000 kms', '55,800 kms', '56,400 kms',
       '72,160 kms', '11,500 kms', '1,33,000 kms', '2,000 kms',
       '88,000 kms', '65,422 kms', '1,17,000 kms', '1,50,000 kms',
       '10,750 kms', '6,800 kms', '5 kms', '9,800 kms', '57,923 kms',
       '30,201 kms', '6,200 kms', '37,518 kms', '24,652 kms', '383 kms',
       '95,000 kms', '3,528 kms', '52,500 kms', '47,900 kms',
       '52,800 kms', '1,95,000 kms', '48,008 kms', '48,247 kms',
       '9,400 kms', '64,000 kms', '2,137 kms', '10,544 kms', '49,500 kms',
       '1,47,000 kms', '90,001 kms', '48,006 kms', '74,000 kms',
       '85,000 kms', '29,500 kms', '39,700 kms', '67,000 kms',
       '19,336 kms', '60,105 kms', '45,933 kms', '1,02,563 kms',
       '28,600 kms', '41,800 kms', '1,16,000 kms', '42,590 kms',
       '7,400 kms', '54,500 kms', '76,000 kms', '00 kms', '11,523 kms',
       '38,600 kms', '95,500 kms', '37,458 kms', '85,960 kms',
       '12,516 kms', '30,600 kms', '2,550 kms', '62,500 kms',
       '69,000 kms', '28,400 kms', '68,485 kms', '3,500 kms',
       '85,455 kms', '63,000 kms', '1,600 kms', '77,000 kms',
       '26,500 kms', '2,875 kms', '13,900 kms', '1,500 kms', '2,450 kms',
       '1,625 kms', '33,400 kms', '60,123 kms', '38,900 kms',
       '1,37,495 kms', '91,200 kms', '1,46,000 kms', '1,00,800 kms',
       '2,100 kms', '2,500 kms', '1,32,000 kms', 'Petrol'], dtype=object)

- year has many non year values
- year obj into int
- price has ask for price
- kms_driven has kms with integer
- kms driven obj into int
- kms_driven has nan values
- fuel_type has nan values
- keep first 3 words of name

# Cleaning

In [9]:
backup = df.copy()

In [10]:
df = df[df['year'].str.isnumeric()]

In [11]:
df['year'] = df['year'].astype(int)

In [12]:
df = df[df['Price'] != 'Ask For Price']

In [13]:
df['Price'] = df['Price'].str.replace(',', '').astype(int)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int32
 3   Price       819 non-null    int32
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.4+ KB

In [15]:
df['kms_driven'] = df['kms_driven'].str.split(" ").str.get(0).str.replace(',', '')

In [16]:
df.head()

,name,company,year,Price,kms_driven,fuel_type
0,Hyundai Santro Xing XO eRLX Euro III,Hyundai,2007,80000,45000,Petrol
1,Mahindra Jeep CL550 MDI,Mahindra,2006,425000,40,Diesel
3,Hyundai Grand i10 Magna 1.2 Kappa VTVT,Hyundai,2014,325000,28000,Petrol
4,Ford EcoSport Titanium 1.5L TDCi,Ford,2014,575000,36000,Diesel
6,Ford Figo,Ford,2012,175000,41000,Diesel

In [17]:
df = df[df['kms_driven'].str.isnumeric()]

In [18]:
df['kms_driven']  = df['kms_driven'].astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32
 3   Price       817 non-null    int32
 4   kms_driven  817 non-null    int32
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB

In [20]:
df = df[~df['fuel_type'].isna()]

In [21]:
df['name'] = df['name'].str.split(" ").str.slice(0,3).str.join(' ')

In [22]:
df.reset_index(drop = True)

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
812          Tata Indica V2      Tata  2009  110000       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
814            Tata Zest XM      Tata  2018  260000       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[816 rows x 6 columns]

In [23]:
df.describe()

              year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [24]:
df = df[df['Price']<6e6].reset_index(drop = True)

In [25]:
df

                       name   company  year   Price  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel
4                 Ford Figo      Ford  2012  175000       41000    Diesel
..                      ...       ...   ...     ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol
811          Tata Indica V2      Tata  2009  110000       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol
813            Tata Zest XM      Tata  2018  260000       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel

[815 rows x 6 columns]

In [26]:
df.to_csv('cleaned_car.csv')

In [27]:
X = df.drop(columns = 'Price')
y = df['Price']

In [28]:
X

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
810      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
811          Tata Indica V2      Tata  2009       30000    Diesel
812    Toyota Corolla Altis    Toyota  2009      132000    Petrol
813            Tata Zest XM      Tata  2018       27000    Diesel
814      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]

In [29]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...
810    270000
811    110000
812    300000
813    260000
814    390000
Name: Price, Length: 815, dtype: int32

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2)

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [32]:
ohe = OneHotEncoder()
ohe.fit(X[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [33]:
ohe.categories_

[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
        'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
        'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat Diesel',
        'Chevrolet Beat LS', 'Chevrolet Beat LT', 'Chevrolet Beat PS',
        'Chevrolet Cruze LTZ', 'Chevrolet Enjoy', 'Chevrolet Enjoy 1.4',
        'Chevrolet Sail 1.2', 'Chevrolet Sail UVA', 'Chevrolet Spark',
        'Chevrolet Spark 1.0', 'Chevrolet Spark LS', 'Chevrolet Spark LT',
        'Chevrolet Tavera LS', 'Chevrolet Tavera Neo', 'Datsun GO T',
        'Datsun Go Plus', 'Datsun Redi GO', 'Fiat Linea Emotion',
        'Fiat Petra ELX', 'Fiat Punto Emotion', 'Force Motors Force',
        'Force Motors One', 'Ford EcoSport', 'Ford EcoSport Ambiente',
        'Ford EcoSport Titanium', 'Ford EcoSport Trend',
        'Ford Endeavor 4x4', 'Ford Fiesta', 'Ford Fiesta SXi', 'Ford Figo',
        'Ford Figo Diesel', 'Ford Figo Duratorq', 'Ford Figo Petrol',
        'Ford Fusion 1.4', 'Ford Ikon 1.3', 'Ford Ikon 1.6',
        'Hindustan Motors Ambassador', 'Honda Accord', 'Honda Amaze',
        'Honda Amaze 1.2', 'Honda Amaze 1.5', 'Honda Brio', 'Honda Brio V',
        'Honda Brio VX', 'Honda City', 'Honda City 1.5', 'Honda City SV',
        'Honda City VX', 'Honda City ZX', 'Honda Jazz S', 'Honda Jazz VX',
        'Honda Mobilio', 'Honda Mobilio S', 'Honda WR V', 'Hyundai Accent',
        'Hyundai Accent Executive', 'Hyundai Accent GLE',
        'Hyundai Accent GLX', 'Hyundai Creta', 'Hyundai Creta 1.6',
        'Hyundai Elantra 1.8', 'Hyundai Elantra SX', 'Hyundai Elite i20',
        'Hyundai Eon', 'Hyundai Eon D', 'Hyundai Eon Era',
        'Hyundai Eon Magna', 'Hyundai Eon Sportz', 'Hyundai Fluidic Verna',
        'Hyundai Getz', 'Hyundai Getz GLE', 'Hyundai Getz Prime',
        'Hyundai Grand i10', 'Hyundai Santro', 'Hyundai Santro AE',
        'Hyundai Santro Xing', 'Hyundai Sonata Transform', 'Hyundai Verna',
        'Hyundai Verna 1.4', 'Hyundai Verna 1.6', 'Hyundai Verna Fluidic',
        'Hyundai Verna Transform', 'Hyundai Verna VGT',
        'Hyundai Xcent Base', 'Hyundai Xcent SX', 'Hyundai i10',
        'Hyundai i10 Era', 'Hyundai i10 Magna', 'Hyundai i10 Sportz',
        'Hyundai i20', 'Hyundai i20 Active', 'Hyundai i20 Asta',
        'Hyundai i20 Magna', 'Hyundai i20 Select', 'Hyundai i20 Sportz',
        'Jaguar XE XE', 'Jaguar XF 2.2', 'Jeep Wrangler Unlimited',
        'Land Rover Freelander', 'Mahindra Bolero DI',
        'Mahindra Bolero Power', 'Mahindra Bolero SLE',
        'Mahindra Jeep CL550', 'Mahindra Jeep MM', 'Mahindra KUV100',
        'Mahindra KUV100 K8', 'Mahindra Logan', 'Mahindra Logan Diesel',
        'Mahindra Quanto C4', 'Mahindra Quanto C8', 'Mahindra Scorpio',
        'Mahindra Scorpio 2.6', 'Mahindra Scorpio LX',
        'Mahindra Scorpio S10', 'Mahindra Scorpio S4',
        'Mahindra Scorpio SLE', 'Mahindra Scorpio SLX',
        'Mahindra Scorpio VLX', 'Mahindra Scorpio Vlx',
        'Mahindra Scorpio W', 'Mahindra TUV300 T4', 'Mahindra TUV300 T8',
        'Mahindra Thar CRDe', 'Mahindra XUV500', 'Mahindra XUV500 W10',
        'Mahindra XUV500 W6', 'Mahindra XUV500 W8', 'Mahindra Xylo D2',
        'Mahindra Xylo E4', 'Mahindra Xylo E8', 'Maruti Suzuki 800',
        'Maruti Suzuki A', 'Maruti Suzuki Alto', 'Maruti Suzuki Baleno',
        'Maruti Suzuki Celerio', 'Maruti Suzuki Ciaz',
        'Maruti Suzuki Dzire', 'Maruti Suzuki Eeco',
        'Maruti Suzuki Ertiga', 'Maruti Suzuki Esteem',
        'Maruti Suzuki Estilo', 'Maruti Suzuki Maruti',
        'Maruti Suzuki Omni', 'Maruti Suzuki Ritz', 'Maruti Suzuki S',
        'Maruti Suzuki SX4', 'Maruti Suzuki Stingray',
        'Maruti Suzuki Swift', 'Maruti Suzuki Versa',
        'Maruti Suzuki Vitara', 'Maruti Suzuki Wagon', 'Maruti Suzuki Zen',
        'Mercedes Benz A', 'Mercedes Benz B', 'Mercedes Benz C',
        'Mercedes Benz GLA', 'Mini Cooper S', 'Mitsubishi Lancer 1.8',
        'Mitsubishi Pajero Sport', 'Nissan Micra XL', 'Nissan Micra XV',
        'Nissan Sunny', 'Nissan Sunny XL', 'Nissan Terrano XL',
        'Nissan X Trail', 'Renault Duster', 'Renault Duster 110',
        'Renault Duster 110PS', 'Renault Duster 85', 'Renault Duster 85PS',
        'Renault Duster RxL', 'Renault Kwid', 'Renault Kwid 1.0',
        'Renault Kwid RXT', 'Renault Lodgy 85', 'Renault Scala RxL',
        'Skoda Fabia', 'Skoda Fabia 1.2L', 'Skoda Fabia Classic',
        'Skoda Laura', 'Skoda Octavia Classic', 'Skoda Rapid Elegance',
        'Skoda Superb 1.8', 'Skoda Yeti Ambition', 'Tata Aria Pleasure',
        'Tata Bolt XM', 'Tata Indica', 'Tata Indica V2', 'Tata Indica eV2',
        'Tata Indigo CS', 'Tata Indigo LS', 'Tata Indigo LX',
        'Tata Indigo Marina', 'Tata Indigo eCS', 'Tata Manza',
        'Tata Manza Aqua', 'Tata Manza Aura', 'Tata Manza ELAN',
        'Tata Nano', 'Tata Nano Cx', 'Tata Nano GenX', 'Tata Nano LX',
        'Tata Nano Lx', 'Tata Sumo Gold', 'Tata Sumo Grande',
        'Tata Sumo Victa', 'Tata Tiago Revotorq', 'Tata Tiago Revotron',
        'Tata Tigor Revotron', 'Tata Venture EX', 'Tata Vista Quadrajet',
        'Tata Zest Quadrajet', 'Tata Zest XE', 'Tata Zest XM',
        'Toyota Corolla', 'Toyota Corolla Altis', 'Toyota Corolla H2',
        'Toyota Etios', 'Toyota Etios G', 'Toyota Etios GD',
        'Toyota Etios Liva', 'Toyota Fortuner', 'Toyota Fortuner 3.0',
        'Toyota Innova 2.0', 'Toyota Innova 2.5', 'Toyota Qualis',
        'Volkswagen Jetta Comfortline', 'Volkswagen Jetta Highline',
        'Volkswagen Passat Diesel', 'Volkswagen Polo',
        'Volkswagen Polo Comfortline', 'Volkswagen Polo Highline',
        'Volkswagen Polo Highline1.2L', 'Volkswagen Polo Trendline',
        'Volkswagen Vento Comfortline', 'Volkswagen Vento Highline',
        'Volkswagen Vento Konekt', 'Volvo S80 Summum'], dtype=object),
 array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
        'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
        'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
        'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
       dtype=object),
 array(['Diesel', 'LPG', 'Petrol'], dtype=object)]

In [34]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_), ['name', 'company', 'fuel_type']),
                                       remainder= 'passthrough')

In [35]:
lr = LinearRegression()

In [36]:
pipe = make_pipeline(column_trans, lr)

In [37]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [38]:
y_pred = pipe.predict(X_test)

In [39]:
r2_score(y_test, y_pred)

0.7275693021491236

In [40]:
scores = []
for i in range(1000):
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=i)
    lr = LinearRegression()
    pipe = make_pipeline(column_trans,lr)
    pipe.fit(X_train, y_train)
    y_pred = pipe.predict(X_test)
    print(r2_score(y_test, y_pred),i)
    scores.append(r2_score(y_test,y_pred))

0.7851075713345007 0
0.5134509653245487 1
0.690367160150539 2
0.5995173244936965 3
0.854043495819585 4
0.7472144396373859 5
0.6257453032026639 6
0.6859713789246265 7
0.7646043999848353 8
0.7310013377473754 9
0.7650688995896291 10
0.7341366536622402 11
0.5285869276344635 12
0.7808569027672924 13
0.7117787376583574 14
0.7412066060471796 15
0.5182544509275677 16
0.7431974336170772 17
0.6922688681859708 18
0.6663299264254802 19
0.6627200983467503 20
0.6597378842088608 21
0.7954262790486668 22
0.6949561169132544 23
0.6238104030004821 24
0.5546156402869495 25
0.7016056777592363 26
0.806492219248423 27
0.8203199577838234 28
0.5884499439879591 29
0.6062729570849448 30
0.6545511608643043 31
0.8020833350647061 32
0.8199298009647127 33
0.5838852694166592 34
0.6876976985816584 35
0.6410278299212379 36
0.7366273518081115 37
0.7158052109514006 38
0.7967377767753616 39
0.3873869280503991 40
0.6742441782975077 41
0.642819444903467 42
0.7471082916212084 43
0.7503558492646559 44
0.7804719193142613 45
0.6222443140333713 46
0.6012243617909581 47
0.8515886638469443 48
0.7314952948422867 49
0.5695512105413234 50
0.5876686426230441 51
0.7465474515341104 52
0.7845370315317419 53
0.7152660835313566 54
0.7170607286745116 55
0.7945927653471099 56
0.7765012940430818 57
0.7886817522114573 58
0.6148134074699569 59
0.6379047346097014 60
0.5817460911480938 61
0.44801490919397946 62
0.6722172056884173 63
0.6629053834108496 64
0.6324631499997116 65
0.4980707882987754 66
0.719474684630411 67
0.6499874347605665 68
0.7882195481384423 69
0.7494361412277527 70
0.7601273085432224 71
0.6760204321781462 72
0.7475778672612607 73
0.6432759980401503 74
0.6716349320773223 75
0.5392373195865119 76
0.5864526345885364 77
0.7658128043998395 78
0.7458545043791287 79
0.6661338690593833 80
0.6427313391908696 81
0.7177444207633219 82
0.765377876873547 83
0.7290154251349882 84
0.6278206252656937 85
0.7990954021308594 86
0.7145450266336439 87
0.6975135402109989 88
0.6928062881260832 89
0.7382924016628758 90
0.6155346163836881 91
0.7738718023982266 92
0.48529716998547734 93
0.7091032911642421 94
0.7082769563377915 95
0.6476549308604354 96
0.7558338120547515 97
0.7722848858299826 98
0.676434180388165 99
0.7138188644496711 100
0.7603881721384603 101
0.7224541481641351 102
0.6790521448207476 103
0.7207027253780425 104
0.6126925464155433 105
0.6658667530517881 106
0.5845330931557838 107
0.756035694885383 108
0.8070900528224949 109
0.7658938919803294 110
0.6627819719099547 111
0.6255987692389519 112
0.7470529374401984 113
0.7428274618483192 114
0.6568728258609636 115
0.6951547234244488 116
0.6662449567056417 117
0.5570043144653323 118
0.8270169408537511 119
0.8131857979838069 120
0.7050710676540578 121
0.7552210905330158 122
0.7133926790021425 123
0.8894326786445936 124
0.7666320753032265 125
0.625550207794215 126
0.6140541369601267 127
0.5877161885097786 128
0.690080096415592 129
0.6367748994963301 130
0.5715527602493662 131
0.7281923038850001 132
0.6907732782304568 133
0.8537827102697378 134
0.8527480461208706 135
0.583571284763676 136
0.7974516439464487 137
0.7218946622465817 138
0.5866970169539812 139
0.8201030413050115 140
0.6767855725866281 141
0.6875780759642707 142
0.7465781475327438 143
0.6627735689125145 144
0.5554604745971738 145
0.7337179101841449 146
0.7340402322540467 147
0.7096980515005713 148
0.6729276300735443 149
0.7679549967369312 150
0.8559988790429665 151
0.6610851442272007 152
0.535982694153079 153
0.6354622911606644 154
0.746405031250728 155
0.497534476722412 156
0.8007533220253742 157
0.6676092842678754 158
0.7647823321030504 159
0.6962387087368181 160
0.7270955686150278 161
0.6854343134261521 162
0.7293194775704941 163
0.6728797018121244 164
0.7818944023690375 165
0.6646970900213272 166
0.529276031237274 167
0.6407778012380143 168
0.7034719924098142 169
0.7100718036420743 170
0.6980447887118469 171
0.8718786387465207 172
0.7626398267871058 173
0.5732886211221927 174
0.6742906295985879 175
0.7897634665898692 176
0.728269629669368 177
0.7703019959509206 178
0.7757708253278746 179
0.7485804582467089 180
0.7046363689605968 181
0.7199021585245633 182
0.6890669331411112 183
0.5108212748579913 184
0.7580815593275078 185
0.7223741772797841 186
0.7287272274070256 187
0.7308537299785215 188
0.6552357242358204 189
0.7316561869100866 190
0.730592493154419 191
0.6955889880973567 192
0.7757951915530065 193
0.800383261920828 194
0.6528370851657765 195
0.7062853878881792 196
0.8130425821521015 197
0.47285964161802196 198
0.8343180910934127 199
0.7139058029465115 200
0.48394700561768045 201
0.6296421667217473 202
0.8326022961215501 203
0.6661414675327133 204
0.762233423462951 205
0.8004689525858235 206
0.5877854870032717 207
0.7606039716463656 208
0.5765958862440332 209
0.5128881986063387 210
0.5992151380215878 211
0.6055503616501765 212
0.726388868824146 213
0.7098775702199734 214
0.7771003573378903 215
0.5469180448436466 216
0.6668006285160226 217
0.6337367900175227 218
0.6247488475381251 219
0.5951043117540877 220
0.752430941995289 221
0.487268222577977 222
0.5065959501010204 223
0.6203861590099466 224
0.8106767561598728 225
0.7475106030850499 226
0.6580401356526324 227
0.7929874758591247 228
0.5793322643288622 229
0.6412760975349946 230
0.6193581609268793 231
0.6858143688598104 232
0.6071227447462044 233
0.7721268684607092 234
0.760965598088665 235
0.7081185477809324 236
0.6125498811441497 237
0.5921802256784545 238
0.5980830808761332 239
0.614719554504186 240
0.4792989867571893 241
0.5859660247992946 242
0.6605215231423965 243
0.48747448209992905 244
0.7961999987896808 245
0.8515316034403851 246
0.7884611034688668 247
0.782321074356874 248
0.5729801732611319 249
0.64310995719617 250
0.5324123174634983 251
0.6020358045560912 252
0.7869147475054885 253
0.5782848962559679 254
0.8069068737101256 255
0.6750940291780524 256
0.7617780437305918 257
0.6556441467946246 258
0.6130155033507927 259
0.7641678992981031 260
0.8075791971882498 261
0.7887544940662934 262
0.7558118495750885 263
0.6952988778969977 264
0.7114428083761327 265
0.7170126096908387 266
0.7682796332852108 267
0.6025090178825687 268
0.5380173922889631 269
0.7257365663003168 270
0.5753870755241429 271
0.689195380191674 272
0.7227863823066256 273
0.7744626059070441 274
0.6512208794513856 275
0.8179261107774413 276
0.7414936006645749 277
0.7520813908505095 278
0.8764997794393199 279
0.6714985778702167 280
0.7635725869315554 281
0.7187520698098733 282
0.8070600175742451 283
0.7534396962926305 284
0.6434743944009405 285
0.7847418562118689 286
0.5728473358706148 287
0.5823943089581392 288
0.5169259210982502 289
0.538314492161182 290
0.7403929230115003 291
0.6200187477275405 292
0.7906652449105802 293
0.8276614883716762 294
0.7624780822159317 295
0.7841811516427338 296
0.7614973525300653 297
0.5399367772275718 298
0.806823237752875 299
0.8309639094060789 300
0.8319576793168526 301
0.7810595072917532 302
0.595871647304139 303
0.6776662871201968 304
0.6477291890080399 305
0.8268221605976027 306
0.7376385188007821 307
0.7674098318408685 308
0.7725900679602424 309
0.7343045553036671 310
0.6321779371677468 311
0.5445195726945975 312
0.49267879776125545 313
0.5984173952377607 314
0.8120973501662039 315
0.627502571904885 316
0.7412544386793571 317
0.6980636150918214 318
0.6154422334841355 319
0.4944054217031676 320
0.7397406113281708 321
0.586742048090477 322
0.5852506345724514 323
0.6660887766860842 324
0.5978016445743102 325
0.7008208873350641 326
0.864053258975542 327
0.7728047193487517 328
0.6058680753908298 329
0.6383774969569803 330
0.523883658662704 331
0.647825063764591 332
0.6706123956432064 333
0.7999186789993428 334
0.7101765954211703 335
0.6584982925269827 336
0.7942772581429147 337
0.6835392766481909 338
0.5881927495550492 339
0.795886409995086 340
0.7811650263440031 341
0.6661893157480585 342
0.7335604148883443 343
0.7747898927136628 344
0.7312664767484407 345
0.7339777741414049 346
0.5921851194076762 347
0.7411376507994554 348
0.6344934562270834 349
0.7675974993059813 350
0.8637910437456688 351
0.7011799885110861 352
0.5457102755150781 353
0.7611631032232546 354
0.8115707983931493 355
0.7998398815635717 356
0.6701250144542679 357
0.7208865326903522 358
0.6286606626911171 359
0.710825189310975 360
0.7367593979422413 361
0.609546403545237 362
0.758793573737008 363
0.7862121238057858 364
0.5795890412553526 365
0.7675915321798075 366
0.45017054072507123 367

0.7675273863079506 368
0.7923528198525501 369
0.7070827281101348 370
0.6626444690181227 371
0.6810213243883327 372
0.7068073108375658 373
0.5696043375050515 374
0.6744686251572238 375
0.7343582019056756 376
0.6574810835859519 377
0.794640376357534 378
0.7977902855706318 379
0.6499494314851325 380
0.7266756629794979 381
0.7800218726678083 382
0.8318897570587231 383
0.7358770753187419 384
0.7926147520283049 385
0.7496114700580822 386
0.7755623773256017 387
0.5684559949771681 388
0.5892356018632219 389
0.777393229182461 390
0.6225569706648446 391
0.8540424411667191 392
0.44297814607911146 393
0.6964322404192844 394
0.7724083997293743 395
0.6553385960238651 396
0.6801840998970208 397
0.6851494672195415 398
0.7422544395965364 399
0.7175540550509294 400
0.682326398378784 401
0.5327604752853101 402
0.4820936942028654 403
0.6798442895261275 404
0.661724487958741 405
0.5517049963811421 406
0.7064539338713951 407
0.7733446130921919 408
0.724964571948427 409
0.7768127380893699 410
0.6753948751526998 411
0.7617455573102638 412
0.5954241668131628 413
0.5946303857929236 414
0.5603535417326377 415
0.5064273472547233 416
0.7450069841788362 417
0.7448144600862594 418
0.8101852897066528 419
0.768414036309856 420
0.6715757619523535 421
0.746267198635314 422
0.7007586483608677 423
0.6840208288005627 424
0.6106227667558868 425
0.47597654518696786 426
0.771462739670248 427
0.7074872734884776 428
0.6538795424143579 429
0.7839743139666757 430
0.8042973680636243 431
0.6427470305266794 432
0.849000419524921 433
0.624589400403726 434
0.8189657402553726 435
0.570612513127843 436
0.7515123250020097 437
0.7037686601645192 438
0.7803696649401071 439
0.7768329728478494 440
0.8345202878158955 441
0.6345832748803519 442
0.8677600849703737 443
0.8369585670877044 444
0.8204547525900843 445
0.7277025364311878 446
0.7015844256966639 447
0.7823117448265516 448
0.781730227903799 449
0.7550995423151899 450
0.6388924322528989 451
0.6018448562788556 452
0.6884753613958572 453
0.7694544266706067 454
0.7044510667513004 455
0.49632901885295666 456
0.5774634515424636 457
0.8023960183962345 458
0.7462018919566586 459
0.7788328410341324 460
0.7325554957938114 461
0.6765966068040857 462
0.7917612505735117 463
0.6221193744258974 464
0.6447131905644766 465
0.7000943743745371 466
0.549403434663392 467
0.7252669051989281 468
0.7788757790400235 469
0.5274847191222221 470
0.5816379505051265 471
0.3858199015283349 472
0.7192990684493736 473
0.6997132335304765 474
0.7864415287834565 475
0.6317000518998364 476
0.7790974502378594 477
0.8320720545882381 478
0.5955143952181923 479
0.6610154110656652 480
0.718175724698348 481
0.6756438867934549 482
0.54264874687538 483
0.7159247080233888 484
0.5598881596306349 485
0.7154504294626575 486
0.6208832643127423 487
0.7528156362336077 488
0.6259286257792365 489
0.5701431380422644 490
0.7817986234175377 491
0.6827038699028775 492
0.7029603823451527 493
0.8125062678094133 494
0.6454624855440676 495
0.8100026624358361 496
0.7091011666134271 497
0.6311459071660364 498
0.8188666872778594 499
0.7691528386284149 500
0.5988284919311199 501
0.5946808579611537 502
0.7296542206881 503
0.5322546618214063 504
0.701779029561127 505
0.7413161082657804 506
0.8367385841982524 507
0.7470555817826126 508
0.7217423086756949 509
0.6993111860974628 510
0.6313470353213053 511
0.6322517186826195 512
0.7475873511284196 513
0.7153539636061472 514
0.8706214475731978 515
0.7881137898292706 516
0.793923616174384 517
0.653537794250771 518
0.7942374472613944 519
0.7697671131599362 520
0.7092172202250628 521
0.5163357201218096 522
0.5879327415902831 523
0.5412932255147396 524
0.44216360735392235 525
0.7723201255933512 526
0.8075880872776607 527
0.8175625174019634 528
0.6540270986912428 529
0.7084732068721757 530
0.7075285402908773 531
0.7560570245839491 532
0.7674558275319304 533
0.5073861389356504 534
0.5920324271323971 535
0.768488964049978 536
0.5428369469883629 537
0.7158013291763177 538
0.7086107139308615 539
0.7562405431003385 540
0.7043137513641271 541
0.7920657658905254 542
0.5844510646353731 543
0.7739669210075825 544
0.5388659729457769 545
0.745349350155962 546
0.3484225251919384 547
0.7768855026515332 548
0.5838264703073162 549
0.6806796315826695 550
0.6877314947543165 551
0.6848196949160803 552
0.7569152240907265 553
0.6546714013528221 554
0.8607591528607526 555
0.6738947171440792 556
0.5241635237192741 557
0.8291952887913641 558
0.7977342046935226 559
0.70721035869359 560
0.5545633432958895 561
0.8182259424256365 562
0.6319708405904296 563
0.6715759339326659 564
0.8006219197742501 565
0.8398568550547473 566
0.7639610499158389 567
0.7407360133231586 568
0.7494827219052795 569
0.7376357744573274 570
0.6926172581553516 571
0.7292606260743948 572
0.7282993190370661 573
0.618275110890472 574
0.728157549130922 575
0.7266210618899611 576
0.7613746472887263 577
0.7843249143407639 578
0.6425952125878462 579
0.6185585336845945 580
0.7210293840302162 581
0.5546715200510403 582
0.6412684747105212 583
0.6092801023015675 584
0.5691422630688522 585
0.7065533605893664 586
0.6265199750716172 587
0.7406688131968334 588
0.7524184034745656 589
0.6677549402461408 590
0.745699644051784 591
0.7630183634515632 592
0.8192341520113864 593
0.6481491148077325 594
0.414293120346664 595
0.6134535737189206 596
0.6741444006763894 597
0.6374885891815241 598
0.5138387339662742 599
0.5078718884852373 600
0.5614112090899976 601
0.7597970634604098 602
0.6432003539548348 603
0.6776941022081782 604
0.7647941538019063 605
0.5337941486033059 606
0.6043246711267032 607
0.8106816408056656 608
0.6627726666137406 609
0.5679779320480502 610
0.6590820592748428 611
0.6271324261455529 612
0.6625262688942235 613
0.7877302807418363 614
0.5969211552377856 615
0.3561430931476487 616
0.7149296494538444 617
0.7279772693400599 618
0.6396345325800668 619
0.6781577006945961 620
0.7460637137755385 621
0.6441040440226173 622
0.5722470603605736 623
0.8037251631023398 624
0.7460919842507587 625
0.679937082934174 626
0.6441029106497864 627
0.7550362934809871 628
0.7094957814920589 629
0.6864776704185263 630
0.752312567065468 631
0.6680987215090473 632
0.6384183960779753 633
0.5429386770021682 634
0.6368510992813682 635
0.6643316133993513 636
0.747497769431688 637
0.7776843182961133 638
0.5567805938586057 639
0.6518356411601477 640
0.7430747110832308 641
0.6981157596128322 642
0.7322353789565939 643
0.5161716456765888 644
0.7719160386591106 645
0.7719058056057263 646
0.5224038569966547 647
0.6991886565492014 648
0.7001073199056722 649
0.6720311700902681 650
0.6482926664476178 651
0.8689034821354739 652
0.7989356416741473 653
0.8057092371073804 654
0.74069956486159 655
0.5976231706217563 656
0.5498307552438251 657
0.7652604130318523 658
0.7531978696807556 659
0.6925244811219007 660
0.8897708995195878 661
0.6252051996533777 662
0.5494234344745152 663
0.5212383422274642 664
0.7220300802544878 665
0.7704375740175786 666
0.7784736902031313 667
0.7767775674014172 668
0.8007339990611586 669
0.8313041018598193 670
0.5791058561622424 671
0.7049050068021745 672
0.8000288435619678 673
0.8131575338748946 674
0.6360063331629445 675
0.6904099914360928 676
0.6010040457996191 677
0.7654472352901802 678
0.6900380662189274 679
0.6551286826881297 680
0.6056712102166075 681
0.761297441778297 682
0.7270086956025714 683
0.6275884158200642 684
0.7214328925825855 685
0.8722113710076779 686
0.7337633072195575 687
0.6654899023960112 688
0.8162010723734402 689
0.6063706740086252 690
0.7185700918771711 691
0.6499304008846531 692
0.7241785061536443 693
0.7290350097037441 694
0.7766517064786714 695
0.717733469698282 696
0.6227973370957645 697
0.784571370745932 698
0.7278339202369302 699
0.5372748710168587 700
0.7360019711407577 701
0.6705225077741561 702
0.7737839131451638 703
0.6862345033279502 704
0.7322568219029032 705
0.7455452614046141 706
0.7476730928851589 707
0.7196358394123363 708
0.5583044389511999 709
0.6674074481650683 710
0.756175456773625 711
0.8363500069900713 712
0.8320818282489568 713
0.6734173569379838 714
0.7410378817391642 715
0.7716213903664424 716
0.6840662666727804 717
0.42257775432431866 718
0.6939794267355228 719
0.6166419529792184 720
0.6919870062598292 721
0.7766636074236416 722
0.7337675959322938 723
0.6662460257968942 724
0.6630204913375176 725
0.6871927131891846 726
0.7133766949369666 727
0.7075295948058078 728

0.6710968919831473 729
0.7458681932562734 730
0.5432523988829431 731
0.7930115978013216 732
0.7274302097553447 733
0.6332269737118676 734
0.5658020806540984 735
0.6443714646139811 736
0.5818577909644118 737
0.7517804556951495 738
0.630705549878654 739
0.7357331490670956 740
0.654409684708768 741
0.7940211091634544 742
0.7817210492465341 743
0.5806369036856043 744
0.6718416016363451 745
0.7537370208685095 746
0.5620648886372421 747
0.6342855749021803 748
0.5603182876858174 749
0.6011275669897107 750
0.7435196607113648 751
0.7616839036203276 752
0.8062826413838905 753
0.8110341724533063 754
0.6359469036056772 755
0.7581433932772249 756
0.7789688936441264 757
0.5856869535230103 758
0.6881232172351919 759
0.7229235614055116 760
0.7565568656745596 761
0.7461801215950137 762
0.6601454441516654 763
0.6284066119531967 764
0.7058867832530435 765
0.6908380116705497 766
0.6878264736699979 767
0.5380908500871464 768
0.7794773699896973 769
0.6982844290336909 770
0.7037841866677068 771
0.799290754372525 772
0.7544248211095014 773
0.6129535974150992 774
0.7001026874582807 775
0.6397778510811005 776
0.48298077627871105 777
0.7512541601627154 778
0.6908602097244103 779
0.7885325430644596 780
0.794653027297907 781
0.7452179898445769 782
0.7928852037802847 783
0.6573011222935936 784
0.6631645484229503 785
0.6941347160630271 786
0.7418823477319458 787
0.7570457136536957 788
0.4893555412593368 789
0.7815743084384124 790
0.7726891314409057 791
0.8217540597313715 792
0.7494797355548869 793
0.7507021989076401 794
0.6166933338767989 795
0.7799573099722606 796
0.6462636503955095 797
0.7570327630238487 798
0.7488506380298974 799
0.7304065956667212 800
0.5628556795617974 801
0.6006413979420477 802
0.7197723227468309 803
0.646889723674642 804
0.6709346252124542 805
0.6690226865533044 806
0.8089583242774453 807
0.41363866370343483 808
0.6403788707351508 809
0.6559268543149603 810
0.6635561481578777 811
0.7583536461041491 812
0.5567234482880616 813
0.7804623353665251 814
0.7234412248164048 815
0.7017590448424934 816
0.7218598087663828 817
0.7221193746854202 818
0.6659121252646871 819
0.5764552609082224 820
0.8063086149106243 821
0.7769253546546455 822
0.5765053011104138 823
0.5015408656788984 824
0.7918173390548684 825
0.6648452504795581 826
0.8363383251962992 827
0.7610019765711352 828
0.6765201745425982 829
0.5572695824779512 830
0.7983592443867552 831
0.8332911080991209 832
0.6179052991963456 833
0.7807503669310342 834
0.7324577937413208 835
0.6937134229778502 836
0.6444204910751054 837
0.7319105712257998 838
0.6539109481816802 839
0.7966986059191542 840
0.8191297459167723 841
0.7926543111584864 842
0.7825945766510823 843
0.7317390301207105 844
0.5134363121793356 845
0.5969581510495661 846
0.7628422060648042 847
0.67901337392515 848
0.7103022838560711 849
0.8168512081702842 850
0.6594723180745048 851
0.6872139172964642 852
0.6563419382569395 853
0.5557169527419689 854
0.7048453232450289 855
0.6423822815468083 856
0.5387160760405073 857
0.8186940176456299 858
0.5441332228516789 859
0.7930583517089747 860
0.6111861544624835 861
0.6925080051588641 862
0.7075632404543428 863
0.7055106477995923 864
0.5767311959854612 865
0.6852938339033494 866
0.6790342692831121 867
0.5481638782625012 868
0.6872715234595315 869
0.5971794160280723 870
0.5924082388899667 871
0.7521793959078231 872
0.7876201530789362 873
0.74056733496136 874
0.7086858810536132 875
0.7574478964381516 876
0.6991425233198985 877
0.6504948860242519 878
0.8107911812692982 879
0.7627075126491897 880
0.752075187230924 881
0.7283742176315726 882
0.7583581162494397 883
0.7329076172749194 884
0.6298881023288063 885
0.5544312271604732 886
0.6897938104797328 887
0.6472775590237931 888
0.665669440817387 889
0.7290512123195941 890
0.5890888745556058 891
0.6496921819527437 892
0.7318949066290523 893
0.5930420806878229 894
0.4918334861495779 895
0.6977242371738418 896
0.692545931751918 897
0.8359041334968013 898
0.6907109045973981 899
0.7430010961108706 900
0.6311674360874171 901
0.6093402367714388 902
0.8499937333505875 903
0.8295532841495692 904
0.7003204447349936 905
0.8488630498040575 906
0.7250364100478293 907
0.7654145932409497 908
0.7436476124750531 909
0.7732737525782276 910
0.8153910425582735 911
0.6025719301934311 912
0.6383233907321028 913
0.679583419511326 914
0.7692321835855204 915
0.5322781742663392 916
0.555917128015486 917
0.7093887337274316 918
0.5332580723873788 919
0.5953923729250358 920
0.7527345280834575 921
0.798147939734426 922
0.6944451935420239 923
0.6846075286866441 924
0.6364449691195543 925
0.8145247107556738 926
0.7578599250651537 927
0.8050123856610585 928
0.7299868732531533 929
0.6062370034602429 930
0.7478156449619678 931
0.5447261482611407 932
0.7911779212971957 933
0.6786739981777911 934
0.6849273304292979 935
0.7904065101048174 936
0.5709874767095586 937
0.766916406460673 938
0.6398630449689273 939
0.5993153426876128 940
0.6372570711265638 941
0.7092906345383212 942
0.6749187450806804 943
0.7591356383888218 944
0.8127832196593298 945
0.5081681921718906 946
0.5942908987416882 947
0.6775281517598946 948
0.8055896440671462 949
0.5155877659873149 950
0.6948080047909737 951
0.7428756954539432 952
0.7063584989698972 953
0.7359749321946958 954
0.6885000684191789 955
0.6184307375045943 956
0.6734384152128103 957
0.7740651754639318 958
0.7642221360259678 959
0.5316977035351241 960
0.7249531998449195 961
0.6993756596511527 962
0.5376185405913569 963
0.612007141676839 964
0.70576802434712 965
0.7868068603944492 966
0.8635780230308187 967
0.695647083629075 968
0.773169416691037 969
0.5359235481371817 970
0.613124112904708 971
0.7106219868945409 972
0.6267159167474534 973
0.753760658402832 974
0.6724175613566397 975
0.6989829791356202 976
0.7692451707478781 977
0.7220108686143931 978
0.4395977298583481 979
0.6287817901300989 980
0.8096902506297297 981
0.744730363682883 982
0.730906411581627 983
0.5909747606081427 984
0.6633017717217353 985
0.8212469029489334 986
0.6883047657423627 987
0.7794191245047253 988
0.8057008848061891 989
0.6235122054197373 990
0.6873577570433248 991
0.7255916971703485 992
0.7582191171399413 993
0.7391199579217673 994
0.6956668990211867 995
0.7689080243142391 996
0.7899356983802228 997
0.6167562463451306 998
0.6360176441761718 999

In [41]:
np.argmax(scores)

661

In [42]:
scores[np.argmax(scores)]

0.8897708995195878

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=np.argmax(scores))
lr = LinearRegression()
pipe = make_pipeline(column_trans,lr)
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test, y_pred))

0.8897708995195878

In [44]:
import pickle

In [45]:
pickle.dump(pipe,open('1LinearRegressionModel.pkl', 'wb'))

In [46]:
pipe.predict(pd.DataFrame([['Maruti Suzuki Swift', 'Maruti', 2019, 100, 'Petrol']],
                          columns= ['name', 'company','year','kms_driven', 'fuel_type']))

array([400803.78418355])